
// Common
export const API_CALL_ERROR = "API_CALL_ERROR";
export const API_CALL_START = "API_CALL_START";
export const LOAD_CATEGORIES = "LOAD_CATEGORIES";


// Employees
export const CREATE_EMPLOYEE = "CREATE_EMPLOYEE";
export const UPDATE_EMPLOYEE = "UPDATE_EMPLOYEE";
export const RETRIEVE_EMPLOYEES = "RETRIEVE_EMPLOYEES";
export const DELETE_EMPLOYEE = "DELETE_EMPLOYEE"
export const SEARCH_EMPLOYEES = "SEARCH_EMPLOYEES"


// Care members
export const CREATE_CARE_MEMBER = "CREATE_CARE_MEMBER";
export const UPDATE_CARE_MEMBER = "UPDATE_CARE_MEMBER"
export const ONBOARD_EMPLOYEES = "ONBOARD_EMPLOYEES";
export const OFFBOARD_CARE_MEMBER = "OFFBOARD_CARE_MEMBER";
export const RESIGN_CARE_MEMBER = "RESIGN_CARE_MEMBER";
export const LOGIN_CARE_MEMBER = "LOGIN_CARE_MEMBER";
export const LOGOUT_CARE_MEMBER = "LOGOUT_CARE_MEMBER";
export const RETRIEVE_CARE_MEMBERS = "RETRIEVE_CARE_MEMBERS";
export const SEARCH_CARE_MEMBERS = "SEARCH_CARE_MEMBERS";
export const CARE_MEMBER_UPDATE_ROLE = "CARE_MEMBER_UPDATE_ROLE";

//CareLead - Group Management Actions
export const CREATE_GROUP = "CREATE_GROUP";
export const DEACTIVATE_GROUP = "DEACTIVATE_GROUP";
export const ADD_CAREMEMBER_TO_GROUP = "ADD_CAREMEMBER_TO_GROUP";
export const REMOVE_CAREMEMBER_FROM_GROUP = "REMOVE_CAREMEMBER_FROM_GROUP";
export const SEARCH_GROUP = "SEARCH_GROUP";
export const RETRIEVE_GROUPS = "RETRIEVE_GROUPS";
export const UPDATE_GROUP = "UPDATE_GROUP"


//CareMember  - Best Practice Management Actions
export const CREATE_BEST_PRACTICE = "CREATE_BEST_PRACTICE";
export const RETRIEVE_BEST_PRACTICES = "RETRIEVE_BEST_PRACTICES";
export const UPDATE_BEST_PRACTICE = "UPDATE_BEST_PRACTICE";
export const ADD_ATTACHMENT_TO_BEST_PRACTICE = "ADD_ATTACHMENT_TO_BEST_PRACTICE" //NB: A redux action might not be needed for this..needs more discussion
export const DELETE_ATTACHMENT_FROM_BEST_PRACTICE = "DELETE_ATTACHMENT_FROM_BEST_PRACTICE"
export const DELETE_BEST_PRACTICE = "DELETE_BEST_PRACTICE";
export const SEARCH_BEST_PRACTICE = "SEARCH_BEST_PRACTICE";
export const RATE_BEST_PRACTICE = "RATE_BEST_PRACTICE";
export const TAG_BEST_PRACTICE = "TAG_BEST_PRACTICE";
export const SHARE_BEST_PRACTICE = "SHARE_BEST_PRACTICE";
export const API_SEND_START = "API_SEND_START";
export const API_SEND_END = "API_SEND_END";


//Admin - Role Management Actions
export const CREATE_ROLE = "CREATE_ROLE";
export const DEACTIVATE_ROLE = "DEACTIVATE_ROLE";
export const EDIT_ROLE = "EDIT_ROLE";
export const RETRIEVE_ROLES = "RETRIEVE_ROLES"

//Care Captain - Training Management Actions
export const ASSIGN_CARE_USER_TO_TRAININGS = "ASSIGN_CARE_USER_TO_TRAININGS";
export const CREATE_TRAINING = "CREATE_TRAINING";
export const EDIT_TRAINING = "EDIT_TRAINING"
export const DEACTIVATE_TRAINING  = "DEACTIVATE_TRAINING";
export const CREATE_TRAINING_TRAIL = "CREATE_TRAINING_TRAIL";
export const ADD_TRAINING_TO_TRAIL = "ADD_TRAINING_TO_TRAIL";
export const REMOVE_TRAINING_FROM_TRAIL = "REMOVE_TRAINING_FROM_TRAIL";

//Maps KPI - Worl Overview Dashboard
export const ALL_ACTIVE_MEMBERS = "ALL_ACTIVE_MEMBERS";
export const NEW_MEMBERS = "NEW_MEMBERS";
export const SELF_RESIGNED_MEMBERS = "SELF_RESIGNED_MEMBERS";
export const AUTO_OFFBOARDED_MEMBERS = "AUTO_OFFBOARDED_MEMBERS";
export const RETRIEVE_EMAIL_DRAFTS = "RETRIEVE_EMAIL_DRAFTS";

//message for authentication
export const LOGIN_SUCCESS = "LOGIN_SUCCESS";
export const LOGIN_FAIL = "LOGIN_FAIL";
export const LOGOUT = "LOGOUT";
export const SET_MESSAGE = "SET_MESSAGE";
export const CLEAR_MESSAGE = "CLEAR_MESSAGE";

